name: dependabot automerge

on:
  pull_request:
    types:
      - opened
      - reopened
    paths:
      - "package.json"
      - "package-lock.json"

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  lint:
    uses: chick-p/github-actions-shared-workflow/.github/workflows/dependabot-automerge.yml@main
